swagger: '2.0'
info:
  title: Religram API
  description: Tài liệu đặc tả API cho phía fontend.
  version: 1.0.0
host: religram.relipa-test.online
basePath: /api/v1
tags:
  - name: auth
    description: Authenticate
  - name: post
    description: API liên quan đến bài post
  - name: user
    description: API dành cho các user
schemes:
  - https
paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: Login
      description: Nhập username (email) và password để login vào ứng dụng
      operationId: 'login'
      parameters:
        - name: body
          in: body
          required: true
          description: Thông tin đăng nhập gồm user (email) và password
          schema:
            $ref: '#/definitions/LoginRequest'
      produces:
        - application/json
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/LoginResponse'
        401:
          description: Unauthorized. Username/password incorrected.

  /auth/signup:
    post:
      tags:
        - auth
      summary: Signup new user
      description: Nhập các thông tin user để đăng ký tài khoản mới
      parameters:
        - name: body
          in: body
          required: true
          description: Thông tin đăng ký tài khoản
          schema:
            $ref: '#/definitions/SignupRequest'
      operationId: 'signup'
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/LoginResponse'
        400:
          description: Validation failed.
        409:
          description: User existed.

  /auth/verify/{token}:
    get:
      tags:
        - auth
      summary: Verify new User
      operationId: 'verifyUser'
      parameters:
        - name: token
          in: path
          required: true
          type: string
      responses:
        200:
          description: Successful operation

  /auth/resetpassword:
    post:
      tags:
        - auth
      summary: Reset password
      operationId: 'resetPassword'
      responses:
        200:
          description: Successful operation

  /auth/changepassword:
    post:
      tags:
        - auth
      summary: Change password
      operationId: 'changePassword'
      responses:
        200:
          description: Successful operation
        401:
          $ref: '#/responses/UnauthorizedError'
      security:
        - religram_auth: []

  /auth/logout:
    get:
      tags:
        - auth
      summary: Logout
      operationId: 'logout'
      responses:
        200:
          description: Successful operation
        401:
          $ref: '#/responses/UnauthorizedError'
      security:
        - religram_auth: []

  /post:
    get:
      tags:
        - post
      summary: Danh sách các post.
      description: 'Trả về danh sách các bài post với các thông tin bao gồm:

 - avatar user (url ảnh)

 - tên user

 - danh sách ảnh up lên

 - số lượng like

 - số lượng comment

 - link api get danh sách user đã like bài post

 - link api get danh sách các comment'
      operationId: "getPostList"
      parameters:
        - name: page
          in: query
          description: Phân trang
          default: 1
          required: true
          type: integer
          format: int32
      produces:
        - application/json
      responses:
        200:
          description: Trả về  danh sách các bài post
          schema:
            type: array
            items:
              $ref: '#/definitions/Post'
        401:
          $ref: '#/responses/UnauthorizedError'
        default:
          description: Unexpected error
      security:
        - religram_auth: []

    post:
      tags:
        - post
      summary: Post bài viết
      description: Dùng để user đăng một bài post mới lên tường trang chủ nhà mình
      operationId: 'newPost'
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: userId
          in: formData
          description: Id của user đang login
          required: true
          type: integer
          format: int64
        - name: content
          in: formData
          description: Caption của post
          type: string
      responses:
        201:
          description: Created
        401:
          $ref: '#/responses/UnauthorizedError'
        500:
          description: Internal Server
      security:
        - religram_auth: []

  /post/{id}:
    get:
      tags:
        - post
      summary: Get post detail
      description: Dùng hiển thị chi tiết bài post
      operationId: 'getPostById'
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Id của bài post
          type: integer
          format: string
          required: true
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/Post'
        401:
          $ref: '#/responses/UnauthorizedError'
      security:
        - religram_auth: []

  /post/{id}/comment:
    get:
      tags:
        - post
      summary: Get list comments of the post
      description: Dùng lấy danh sách các comment của bài post
      operationId: 'getCommentsByPostId'
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          description: Id của bài post
          type: integer
          format: int32
        - name: page
          in: query
          description: Phân trang
          required: true
          type: integer
      responses:
        200:
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Comment'
        401:
          $ref: '#/responses/UnauthorizedError'
        default:
          description: Unexpected error
      security:
        - religram_auth: []

    post:
      tags:
        - post
      summary: Post comment
      description: Đăng bình luận cho 1 bài post
      operationId: 'postCommentByPostId'
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          description: Id của bài post
          type: integer
          format: int32
        - name: body
          in: body
          description: Id của user đang login
          required: true
          schema:
            $ref: '#/definitions/CommentRequest'

      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/Comment'
        401:
          $ref: '#/responses/UnauthorizedError'
      security:
        - religram_auth: []

  /post/{id}/like:
    post:
      tags:
        - post
      summary: Like button
      operationId: 'likePost'
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          description: Id của bài post
          type: integer
          format: int32
        - name: userId
          in: query
          type: integer
          format: int64
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/LikeResponse'
        401:
          $ref: '#/responses/UnauthorizedError'
        default:
          description: Unexpected error
      security:
        - religram_auth: []

  /user/{id}:
    get:
      tags:
        - user
      summary: Get current user info
      description: Sử dụng lấy info trong màn hình profile
      operationId: 'getUserById'
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/User'
        401:
          $ref: '#/responses/UnauthorizedError'
      security:
        - religram_auth: []

    put:
      tags:
        - user
      summary: Update User info
      description: Dungf update thông tin user
      operationId: 'updateUserInfo'
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
        - name: body
          in: body
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: Successful operation
        401:
          $ref: '#/responses/UnauthorizedError'
      security:
        - religram_auth: []

responses:
  UnauthorizedError:
    description: API key is missing or invalid
    headers:
      Authorization:
        description: Bearer {token}
        type: string
securityDefinitions:
  religram_auth:
    type: "apiKey"
    in: header
    name: Authorization

definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      fullname:
        type: string
      email:
        type: string
      avatar:
        type: string
    xml:
      name: User

  Post:
    type: object
    properties:
      id:
        type: integer
        format: int64
      content:
        type: string
      likeCount:
        type: integer
        format: int32
      commentCount:
        type: integer
        format: binary
      user:
        $ref: '#/definitions/User'
      comments:
        type: array
        xml:
          name: comments
          wrapped: true
        items:
          $ref: '#/definitions/Comment'
      isLiked:
        type: boolean
      created_at:
        type: string
      updated_at:
        type: string
      photos:
        type: array
        xml:
          name: photos
          wrapped: true
        items:
          $ref: '#/definitions/Photo'
    xml:
      name: Post

  Photo:
    type: object
    properties:
      id:
        type: integer
        format: int64
      photoUri:
        type: string
      createdAt:
        type: string
      updatedAt:
        type: string
    xml:
      name: Photo

  Comment:
    type: object
    properties:
      id:
        type: integer
        format: int64
      user:
        $ref: '#/definitions/User'
      comment:
        type: string
      createdAt:
        type: string
      updatedAt:
        type: string
    xml:
      name: Comment

  CommentRequest:
    type: object
    properties:
      userId:
        type: integer
        format: int64
      comment:
        type: string
    xml:
      name: CommentBody

  LikeResponse:
    type: object
    properties:
      isLiked:
        type: boolean
      likeCount:
        type: integer
        format: int64
    xml:
      name: LikeResponse

  LoginRequest:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
    xml:
      name: LoginRequest

  SignupRequest:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
      fullname:
        type: string
      email:
        type: string
    xml:
      name: SignupRequest

  LoginResponse:
    type: object
    properties:
      user:
        $ref: '#/definitions/User'
      token:
        type: string
    xml:
      name: LoginResponse


